"""Generate the data-driven parts of the paper figures as TikZ/pgfplots source.

Writes three files under paper/figures from the saved result JSON:

  check_groups.tex  the check-group chips inside the architecture figure
  fault_matrix.tex  the per-fault detection matrix
  leakage.tex       the temporal sensitivity panels

The architecture figure's layout is structural rather than data-driven and stays in
paper/figures/architecture.tex by hand. Every output draws at exactly \\linewidth and
inherits the document font, so no external renderer or image export step is involved.
"""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / 'results'
FIGURES = ROOT / 'paper' / 'figures'

BANNER = ('% Generated by tools/make_paper_figures.py from results/*.json.\n'
          '% Edit the generator, not this file.\n')

# Layer order follows the conversion pipeline shown in the architecture figure.
LAYER_ORDER = ['canonical', 'omop', 'meds']
LAYER_TITLE = {'canonical': 'Canonical layer', 'omop': 'OMOP layer', 'meds': 'MEDS layer'}

# Readable names for the four checks the ablation removes, matching the wording used
# in the text. Keyed by check id so a change to the ablation set is caught here.
EXCLUDED = {
    'ANCHOR_TIMES_ARE_NOT_THE_EVENT_CLOCK': 'anchor clocks',
    'CANONICAL_SCHEMA_AS_DECLARED': 'canonical fields',
    'EVENT_SUBJECTS_WERE_ISSUED_BY_IDENTITY': 'issued identities',
    'OMOP_BIRTH_YEAR_IS_REPRODUCIBLE': 'birth-year provenance',
}

# Column labels. The fault identifiers are too long to set vertically at figure
# size; these are the shortened forms, kept faithful to the identifier.
SHORT = {
    'ANCHOR_USED_AS_EVENT_TIME': 'Anchor as event time',
    'COHORT_LABEL_BECAME_A_DIAGNOSIS': 'Cohort label a diagnosis',
    'IDENTITY_NOT_RESOLVED_ACROSS_PARTITIONS': 'Identity unresolved',
    'LINEAGE_LINKS_DANGLE': 'Lineage links dangle',
    'PARTITION_COLUMN_LEAKED_INTO_CANONICAL': 'Partition column leaked',
    'POST_DEATH_RECORDS_DELETED': 'Post-death rows deleted',
    'QUARANTINE_REASON_ERASED': 'Quarantine reason erased',
    'BIRTH_YEAR_INVENTED_UNDER_STRICT_POLICY': 'Birth year invented',
    'CONCEPT_PLACED_IN_THE_WRONG_DOMAIN': 'Concept in wrong domain',
    'MEASUREMENT_DATE_FABRICATED': 'Measurement date faked',
    'PRIMARY_KEY_COLLISION': 'Primary key collision',
    'WITHHELD_PATIENT_STILL_PUBLISHED': 'Withheld patient published',
    'AVAILABILITY_PRECEDES_OCCURRENCE': 'Availability before event',
    'CODE_METADATA_INCOMPLETE': 'Code metadata incomplete',
    'COHORT_LABEL_LEAKED_INTO_MEDS_EVENTS': 'Cohort label in MEDS',
    'SHARD_NOT_TIME_SORTED': 'Shard not time sorted',
    'SUBJECT_IN_TWO_SPLITS': 'Subject in two splits',
}


# The five groups the architecture figure reports, keyed the same way as the text.
RECONCILIATION = {
    'INPUT_MANIFEST_COMPLETE', 'RECONCILIATION_ROWS', 'SOURCE_COVERAGE_REPORTED',
    'EVENT_LINEAGE_COMPLETE', 'LINK_TARGETS_EXIST', 'FAN_OUT_AND_DEDUP',
    'SOURCE_ROWS_ACCOUNTED',
}
GROUP_LABEL = [
    ('reconciliation', r'Reconciliation\\and lineage'),
    ('semantic', r'Semantic\\correctness'),
    ('omop', r'OMOP\\compliance'),
    ('meds', r'MEDS\\compliance'),
    ('review', r'Review\\governance'),
]


def check_group(check_id):
    if check_id in RECONCILIATION:
        return 'reconciliation'
    if check_id.startswith('MEDS_'):
        return 'meds'
    if check_id.startswith('OMOP_') or check_id == 'TERMINOLOGY_COVERAGE_PLAUSIBLE':
        return 'omop'
    if check_id == 'UNDECIDED_PROPOSALS_NEVER_PUBLISHED':
        return 'review'
    return 'semantic'


def load(name):
    return json.loads((RESULTS / name).read_text())


def fault_matrix():
    full = load('faults_fixture.json')
    ablated = load('faults_fixture_before.json')
    dqd = load('dqd_baseline.json')

    by_id = {r['fault_id']: r for r in full['results']}
    ablated_by_id = {r['fault_id']: r for r in ablated['results']}
    dqd_detected = set(dqd['faults_detected_ids'])
    dqd_unreachable = set(dqd['faults_never_reaching_the_cdm'])

    missing = set(by_id) - set(SHORT)
    if missing:
        raise SystemExit(f'No short label for {sorted(missing)}')

    columns = [fid for layer in LAYER_ORDER
               for fid in sorted(f for f in by_id if by_id[f]['layer'] == layer)]

    def status(fid, row):
        if row == 'dqd':
            if fid in dqd_unreachable:
                return 'scope'
            return 'hit' if fid in dqd_detected else 'miss'
        source = ablated_by_id if row == 'ablated' else by_id
        return 'hit' if source[fid]['detected'] else 'miss'

    rows = [
        ('dqd', 'OHDSI DQD', f"{dqd['checks_total']:,} checks".replace(',', '{,}'),
         f"{dqd['faults_detected']}\\,/\\,{dqd['faults_reaching_the_cdm']}"),
        ('ablated', 'Contract, ablated', f"{ablated['checks_total']} checks",
         f"{ablated['faults_detected']}\\,/\\,{ablated['faults_total']}"),
        ('full', 'Contract', f"{full['checks_total']} checks",
         f"{full['faults_detected']}\\,/\\,{full['faults_total']}"),
    ]

    # Geometry, in units of one hundredth of \linewidth.
    label_w, matrix_x, matrix_w, total_x = 25.0, 27.0, 65.0, 93.5
    col_w = matrix_w / len(columns)
    cell = 3.1
    matrix_top, row_h, group_rule = -29.5, 4.6, -7.0

    out = [BANNER,
           r'\setlength{\figunit}{0.01\linewidth}%',
           r'\begin{tikzpicture}[figbase, x=\figunit, y=\figunit]',
           '',
           '% legend',
           r'\node[bodytext, anchor=north west] at (0,0) '
           r'{\figband{Detection on the 17-fault catalogue}};']

    legend = [('hit', 'Detected'), ('miss', 'Missed'), ('scope', 'Outside tool scope')]
    lx = 48.0
    for key, text in legend:
        out.append(fr'\node[cell{key}, anchor=north west] at ({lx:.2f},-0.4) {{}};')
        out.append(fr'\node[minitext, anchor=north west] at ({lx + 4.0:.2f},-0.15) {{{text}}};')
        lx += 4.0 + 1.05 * len(text) + 2.6

    out.append('')
    out.append('% layer groups')
    for layer in LAYER_ORDER:
        idx = [i for i, f in enumerate(columns) if by_id[f]['layer'] == layer]
        x0 = matrix_x + idx[0] * col_w
        x1 = matrix_x + (idx[-1] + 1) * col_w
        out.append(fr'\draw[black!35, line width=0.4pt] '
                   fr'({x0 + 0.3:.2f},{group_rule:.2f}) -- ({x1 - 0.3:.2f},{group_rule:.2f});')
        out.append(fr'\node[minitext, anchor=south] at ({(x0 + x1) / 2:.2f},{group_rule + 0.2:.2f}) '
                   fr'{{{LAYER_TITLE[layer]}\ ({len(idx)})}};')

    out.append('')
    out.append('% fault names, set vertically above their column')
    for i, fid in enumerate(columns):
        x = matrix_x + (i + 0.5) * col_w
        out.append(fr'\node[minitext, rotate=90, anchor=west, align=left] '
                   fr'at ({x:.2f},{matrix_top + 0.9:.2f}) {{{SHORT[fid]}}};')

    out.append('')
    out.append('% matrix')
    for r, (key, name, sub, total) in enumerate(rows):
        yc = matrix_top - (r + 0.5) * row_h
        out.append(fr'\node[bodytext, anchor=east, align=right] at ({label_w:.2f},{yc:.2f}) '
                   fr'{{{name}\\[-0.2\figunit]\figmini{{{sub}}}}};')
        for i, fid in enumerate(columns):
            x = matrix_x + (i + 0.5) * col_w
            out.append(fr'\node[cell{status(fid, key)}, minimum size={cell}\figunit] '
                       fr'at ({x:.2f},{yc:.2f}) {{}};')
        out.append(fr'\node[bodytext, anchor=west] at ({total_x:.2f},{yc:.2f}) '
                   fr'{{\bfseries {total}}};')

    matrix_bottom = matrix_top - len(rows) * row_h
    out.append('')
    out.append('% group separators')
    for layer in LAYER_ORDER[1:]:
        i = next(i for i, f in enumerate(columns) if by_id[f]['layer'] == layer)
        x = matrix_x + i * col_w
        out.append(fr'\draw[black!20, line width=0.4pt] '
                   fr'({x:.2f},{matrix_top - 0.4:.2f}) -- ({x:.2f},{matrix_bottom + 0.4:.2f});')

    unknown = set(ablated['excluded_checks']) - set(EXCLUDED)
    if unknown:
        raise SystemExit(f'No readable name for excluded check {sorted(unknown)}')
    names = [EXCLUDED[c] for c in ablated['excluded_checks']]
    removed = ', '.join(names[:-1]) + f', and {names[-1]}'
    out.append('')
    out.append(fr'\draw[black!25, line width=0.4pt] '
               fr'(0,{matrix_bottom - 2.4:.2f}) -- (100,{matrix_bottom - 2.4:.2f});')
    out.append(fr'\node[minitext, anchor=north west, text width=100\figunit] '
               fr'at (0,{matrix_bottom - 3.6:.2f}) {{The ablation removes the '
               fr'{len(names)} artifact checks on {removed}. The '
               # A raw f-string would keep the backslash and LaTeX would read \'s as an accent.
               fr"{len(dqd_unreachable)} faults outside DQD's reach never arrive in an "
               fr'OMOP table.}};')
    out.append(r'\end{tikzpicture}')
    (FIGURES / 'fault_matrix.tex').write_text('\n'.join(out) + '\n')
    return len(columns), rows


def leakage():
    data = load('leakage_downstream.json')
    horizons = data['horizons']
    arms = [('respects_availability', 'Availability filter', 'armfilter'),
            ('ignores_availability', 'Availability ignored', 'armignored'),
            ('diagnoses_at_admission', 'Diagnosis backdating', 'armdated')]

    # Horizons double, so plotting them at equal spacing is a base-2 log axis. It is
    # drawn as an index axis rather than xmode=log: pgfplots misroutes a style-supplied
    # xmode when the same style is re-read for a log-scaled y axis.
    positions = {h['horizon_hours']: i + 1 for i, h in enumerate(horizons)}
    labels = ','.join(str(h['horizon_hours']) for h in horizons)
    xticks = ','.join(str(i + 1) for i in range(len(horizons)))

    def value(h, arm, field):
        return next(a for a in h['arms'] if a['arm'] == arm)[field]

    out = [BANNER,
           r'\setlength{\figunit}{0.01\linewidth}%',
           r'\begin{tikzpicture}[figbase]',
           r'\begin{groupplot}[group style={group size=3 by 1, horizontal sep=9mm},',
           r'  width=0.29\linewidth, height=33mm, leakpanel,',
           fr'  xtick={{{xticks}}}, xticklabels={{{labels}}},]']

    panels = [('held_out_auroc', '(a) AUROC', 'ymin=0.80, ymax=1.00, '
               'ytick={0.80,0.85,0.90,0.95,1.00}, '
               'yticklabels={0.80,0.85,0.90,0.95,1.00}', True),
              ('held_out_auprc', '(b) AUPRC', 'ymin=0, ymax=0.80, '
               'ytick={0,0.2,0.4,0.6,0.8}, '
               'yticklabels={0.00,0.20,0.40,0.60,0.80}', False)]
    for i, (field, title, yaxis, legend) in enumerate(panels):
        opts = [f'title={{{title}}}', yaxis]
        if legend:
            opts.append('legend to name=leakagelegend, legend columns=3')
        if i == 1:
            opts.append('xlabel={Hours after admission}')
        out.append(fr'\nextgroupplot[{", ".join(opts)}]')
        for arm, label, style in arms:
            coords = ' '.join(f'({positions[h["horizon_hours"]]},{value(h, arm, field)})'
                              for h in horizons)
            out.append(fr'\addplot[{style}] coordinates {{{coords}}};')
            if legend:
                out.append(fr'\addlegendentry{{{label}}}')

    # Third panel: increase in AUROC over the availability filter. Panel (a) cannot
    # separate the two filtered arms; on a log scale their difference is legible.
    out.append(r'\nextgroupplot[title={(c) AUROC increase},')
    out.append(r'  ymode=log, ymin=0.0015, ymax=0.30, ytick={0.002,0.01,0.05,0.2},')
    out.append(r'  yticklabels={0.002,0.010,0.050,0.200},]')
    for arm, _, style in arms[1:]:
        coords = ' '.join(f"({positions[h['horizon_hours']]},{h['auroc_inflation'][arm]})"
                          for h in horizons)
        out.append(fr'\addplot[{style}] coordinates {{{coords}}};')
    out.append(r'\end{groupplot}')


    out.append(r'\end{tikzpicture}')
    # The shared legend is set outside the picture: groupplots does not expose stable
    # node names for its axes, and \centering in the float centres it on the text width.
    out.append(r'\\[1.5mm]')
    out.append(r'\ref{leakagelegend}')
    (FIGURES / 'leakage.tex').write_text('\n'.join(out) + '\n')
    return len(horizons)


def check_groups():
    """Emit the architecture figure's chip row from the live check registry."""
    ids = load('paper_snapshot.json')['registered_check_ids']
    counts = {}
    for check_id in ids:
        counts[check_group(check_id)] = counts.get(check_group(check_id), 0) + 1
    if sum(counts.values()) != len(ids):
        raise SystemExit('Check grouping lost a check')
    rows = ',\n'.join(f'                        {i}/{counts[key]}/{{{label}}}'
                       for i, (key, label) in enumerate(GROUP_LABEL))
    body = (BANNER +
            '\\foreach \\i/\\n/\\lab in {' + rows.lstrip() + '}{%\n'
            '  \\node[chip, anchor=north west, minimum width=18\\figunit,'
            ' minimum height=7.8\\figunit,\n'
            '        text width=16.2\\figunit]\n'
            '    at ({2 + \\i*19.5},-43.4) {\\figcount{\\n}\\\\[0.1\\figunit]'
            '{\\centering\\figmini{\\lab}}};\n}\n')
    (FIGURES / 'check_groups.tex').write_text(body)
    return len(ids), counts


def main():
    total, counts = check_groups()
    columns, rows = fault_matrix()
    n = leakage()
    print(f'Wrote check_groups.tex ({total} checks: '
          + ', '.join(f'{k} {v}' for k, v in counts.items()) + ')')
    print(f'Wrote fault_matrix.tex ({len(rows)} detectors x {columns} faults) '
          f'and leakage.tex ({n} horizons x 3 arms).')


if __name__ == '__main__':
    main()
